### PR TITLE
Tell people that modules include docs

### PR DESCRIPTION
**Pull request by gundalow**

### CODE REVIEW

**Review by trishnaguha — APPROVED** [review]

**Comment by trishnaguha** [comment]
We can also have this in the main repo.

**Comment by gundalow** [comment]
@trishnaguha Yup, will do. Though using this to test zuul merging

Related PR https://github.com/ansible-network/zuul-config/pull/16/files

**Comment by gundalow** [comment]
Please do NOT merge, testing Zuul

**Comment by gundalow** [comment]
recheck

**Pull request merged**
