### PR TITLE
Sync from upstream

### PR DESCRIPTION
**Pull request by gundalow**
Pull in changes from `network-engine` into `network-engine-zuul`

### CODE REVIEW

**Comment by gundalow** [comment]
recheck

**Comment by gundalow** [comment]
recheck

**Comment by morucci** [comment]
recheck

**Comment by morucci** [comment]
recheck

**Comment by gundalow** [comment]
Legitimate failures which I'll fix upstream (in `network-engine`) then rebase this PR

**Comment by gundalow** [comment]
* Updated to use ansible-test from `stable-2.5`
* Allow `removed_in: `2.6"`

**Comment by gundalow** [comment]
recheck

**Comment by gundalow** [comment]
Remaining issues will pass once
* ~~https://github.com/ansible-network/network-engine/pull/82 is merged and this PR is updated~~ MERGED
* Removed duplicated (broken) anchors in `CHANGELOG.rst`
* ~~Correct `meta` link to role~~ DONE

**Comment by gundalow** [comment]
recheck

**Review by trishnaguha — APPROVED** [review]

**Pull request merged**
